config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  resources :books do
    resources :reviews
  end
  get 'password/reset', to: 'password_reset#new', as: :password_reset
  post 'password/reset', to: 'password_reset#create'
  get 'password/reset/edit', to: 'password_reset#edit'
  patch 'password/reset/edit', to: 'password_reset#update'
  get 'password', to: 'password#edit', as: :edit_password
  patch 'password', to: 'password#update'
  delete 'logout', to: 'sessions#destroy'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'login/index'
  root to: 'books#index' 
  get 'history/index'
  get 'about/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :reviews
    has_one_attached :book_img
    has_many :orderables
    has_many :carts, through: :orderables
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :orderables
    has_many :books, through: :orderables

    def total
        orderables.to_a.sum {|orderable| orderable.total}
    end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :book
  belongs_to :cart

  def total
    book.price * quantity
  end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :book
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :books
    has_many :reviews
    has_secure_password


    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address"}
    validates :password, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :find_book, only: [:show, :edit, :update, :destroy]
    def index
        if params[:category].blank?
        @books = Book.all.order("created_at DESC")
        else
            @category_id= Category.find_by(name: params[:category]).id
            @books = Book.where(:category_id => @category_id).order("created_at DESC")
        end
    end
    def show
        if @book.reviews.blank?
            @average_review = 0
        else
            @average_review = @book.reviews.average(:rating).round(2)
        end
    end
    def edit
        @categories = Category.all.map{ |c| [c.name, c.id]}
    end
    def update
        @book.category_id = params[:category_id]
        if @book.update(book_params)
            redirect_to book_path(@book)
        else
            render 'edit'
        end

    end
    def destroy
        @book.destroy
        redirect_to root_path
    end
    def new 
        @book =  Current.user.books.build
        @categories = Category.all.map{ |c| [c.name, c.id]}
    end
    def create
        @book = Current.user.books.build(book_params)
        @book.category_id = params[:category_id]
        
        if @book.save
            redirect_to root_path
        else
            redirect_to 'new'
        end
    end

    private

    def book_params
        params.require(:book).permit(:title, :description, :author, :category_id, :book_img, :price)
    end
    def find_book
        @book = Book.find(params[:id])
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
  end

  def add
    @book = Book.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(book_id: @book.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity: quantity)
    elsif quantity <=0
      current_orderable.destroy
    else
      @cart.orderables.create(book: @book, quantity: quantity)
  end
  respond_to do |format|
    format.turbo_stream do
      render turbo_stream: [turbo_stream.replace('cart',
                                                 partial: 'cart/cart',
                                                 locals: { cart: @cart })]
    end
  end
end


  def remove
    Orderable.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('cart',
                                                  partial: 'cart/cart',
                                                  locals: { cart: @cart })
      end
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    # flash.now[:notice] = 'Logged in successfully'
    # flash.now[:alert] = 'Invalid email or password'
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/crew_helper.rb
module CrewHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/cart/_cart.html.erb
<style>
.cart-box {
  border: 1px solid #ddd;
  padding: 20px;
  width: 300px;
}

.cart-box h2 {
  margin-top: 0;
}

.check-cart-btn {
  display: inline-block;
  margin-top: 10px;
  padding: 10px 20px;
  background-color: #0080ff;
  color: #fff;
  text-decoration: none;
}

.check-cart-btn:hover {
  background-color: #0066cc;
}

.cart-box p {
  margin-top: 10px;
  font-size: 1.2rem;
  font-weight: bold;
}
</style>
<%= turbo_frame_tag "cart" do %>
<div class="cart-box">
<h2>Cart</h2>
<%= link_to "Check Cart", cart_path(@cart), class: "check-cart-btn" %>
<% if @cart.orderables.count > 0 %>
<%= render "cart/orderables"%>
<p>Total: <%= @cart.total%></p>
<%else%>
<p>Your cart is empty</p>
<%end%>
<%end%>
</div>

app/views/cart/_orderables.html.erb
<style>
/* The cart container */
#cart-container {
  display: flex;
  flex-direction: column;
  position: fixed;
  top: 62px;
  right: 0;
  width: 300px;
  height: calc(100vh - 50px);
  overflow-y: auto;
  padding: 20px;
}

/* The individual cart item */
.cart {
  border: 1px solid black;
  padding: 10px;
  text-align: center;
  background: aliceblue;
  display: inline-block;
  flex-direction: column;
  line-height: 2.5rem;
}

.cart-row {
  display: flex;
  justify-content: space-between;
}

.cart-label {
  font-weight: bold;
  margin-right: 10px;
}

.cart-value {
  flex-grow: 1;
}

.cart strong {
  display: block;
  margin-bottom: 10px;
}

.cart input[type="number"] {
  width: 50px;
  margin-right: 5px;
}

.cart input[type="submit"] {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 5px 10px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 14px;
  margin: 4px 2px;
  cursor: pointer;
}

.cart input[type="submit"]:hover {
  background-color: #3e8e41;
}

.cart form {
  display: inline-block;
}
</style>

<div id="cart-container">
  <% @cart.orderables.each do |orderable| %>
    <% book = orderable.book %>

    <div id="<%= "cart-#{book.id}"%>">
      <div class="cart">
        <div class="cart-row">
          <div class="cart-label">Name:</div>
          <div class="cart-value"><%= book.title %></div>
        </div>

        <div class="cart-row">
          <div class="cart-label">Price:</div>
          <div class="cart-value"><%= book.price %></div>
        </div>

        <%= form_with(url: cart_add_path) do |f| %>
          <%= f.hidden_field :id, value: book.id%>
          <%= f.number_field :quantity, value: orderable.quantity, min: 0%>
          <%= f.submit "Add To Cart"%>
        <%end%>

        <%= form_with(url: cart_remove_path) do |f| %>
          <%= f.hidden_field :id, value: orderable.id%>
          <%= f.submit "X"%>
        <%end%>

        <div class="cart-row">
          <div class="cart-label">Total:</div>
          <div class="cart-value"><%= orderable.total %></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/cart/show.html.erb
<h1>Your Cart</h1>
<% @cart.orderables.each do |orderable| %>
  <% book = orderable.book %>
  <p><%= book.title %> * <%= orderable.quantity %> = $<%= book.price * orderable.quantity %></p>
<% end %>
<p>Your total is $<%= @cart.total %> </p>