config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  resources :books do
    resources :reviews
  end
  get 'password/reset', to: 'password_reset#new', as: :password_reset
  post 'password/reset', to: 'password_reset#create'
  get 'password/reset/edit', to: 'password_reset#edit'
  patch 'password/reset/edit', to: 'password_reset#update'
  get 'password', to: 'password#edit', as: :edit_password
  patch 'password', to: 'password#update'
  delete 'logout', to: 'sessions#destroy'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'login/index'
  root to: 'books#index' 
  get 'history/index'
  get 'about/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :reviews
    has_one_attached :book_img
    has_many :orderables
    has_many :carts, through: :orderables
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :orderables
    has_many :books, through: :orderables

    def total
        orderables.to_a.sum {|orderable| orderable.total}
    end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :book
  belongs_to :cart

  def total
    book.price * quantity
  end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :book
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :books
    has_many :reviews
    has_secure_password


    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address"}
    validates :password, presence: true
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
  end

  def add
    @book = Book.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(book_id: @book.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity: quantity)
    elsif quantity <=0
      current_orderable.destroy
    else
      @cart.orderables.create(book: @book, quantity: quantity)
  end
  respond_to do |format|
    format.turbo_stream do
      render turbo_stream: [turbo_stream.replace('cart',
                                                 partial: 'cart/cart',
                                                 locals: { cart: @cart })]
    end
  end
end


  def remove
    Orderable.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('cart',
                                                  partial: 'cart/cart',
                                                  locals: { cart: @cart })
      end
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/crew_helper.rb
module CrewHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>
  <div class="container">
  <%= render partial: "shared/flash" %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-success mt-4">
<%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-danger mt-4">
<%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<style>
      .dropdown-menu-dark a {
        color: black !important;
      }
    </style>

<nav class="navbar navbar-expand-lg navbar-dark bg-light bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/history/index">History</a>
        </li >
        

      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
            <% Category.all.each do |category| %>
           <li class="<%= 'active' if params[:category] == category.name %>">
           <%= link_to category.name, books_path(category: category.name), class: "nav-link" %>
           </li>
           <% end %>
          </ul>
        </li>
      </ul>

      </ul>


      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <% if Current.user %>
      <li class="nav-item">
       <%= link_to Current.user.email, edit_password_path, class: "nav-link" %></span>
      </li>
        <li class="nav-item">
        <%= link_to "Add Book", new_book_path, class: "nav-link" %>
        </li>
      <li class="nav-item">
      <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
    </li>

    <%else%>
    <li class="nav-item">
    <%= link_to "Sign Up", sign_up_path, class: "nav-link"%>
    </li>
    <li class="nav-item">
    <%= link_to "Login", sign_in_path, class: "nav-link"%>
    </li>
<%end%>
      </ul>


    </div>
  </div>
</nav>