config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  resources :books do
    resources :reviews
  end
  get 'password/reset', to: 'password_reset#new', as: :password_reset
  post 'password/reset', to: 'password_reset#create'
  get 'password/reset/edit', to: 'password_reset#edit'
  patch 'password/reset/edit', to: 'password_reset#update'
  get 'password', to: 'password#edit', as: :edit_password
  patch 'password', to: 'password#update'
  delete 'logout', to: 'sessions#destroy'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'login/index'
  root to: 'books#index' 
  get 'history/index'
  get 'about/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :reviews
    has_one_attached :book_img
    has_many :orderables
    has_many :carts, through: :orderables
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :orderables
    has_many :books, through: :orderables

    def total
        orderables.to_a.sum {|orderable| orderable.total}
    end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :book
  belongs_to :cart

  def total
    book.price * quantity
  end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :book
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :books
    has_many :reviews
    has_secure_password


    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address"}
    validates :password, presence: true
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
  end

  def add
    @book = Book.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(book_id: @book.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity: quantity)
    elsif quantity <=0
      current_orderable.destroy
    else
      @cart.orderables.create(book: @book, quantity: quantity)
  end
  respond_to do |format|
    format.turbo_stream do
      render turbo_stream: [turbo_stream.replace('cart',
                                                 partial: 'cart/cart',
                                                 locals: { cart: @cart })]
    end
  end
end


  def remove
    Orderable.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('cart',
                                                  partial: 'cart/cart',
                                                  locals: { cart: @cart })
      end
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    # flash.now[:notice] = 'Logged in successfully'
    # flash.now[:alert] = 'Invalid email or password'
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_book
    before_action :find_review, only: [:edit, :update, :destroy]
    def new
        @review = Review.new
    end

    def edit
    end

    def destroy
        @review.destroy
        redirect_to book_path(@book)
    end

    def update

        if @review.update(review_params)
            redirect_to book_path(@book)
        else
            render 'edit'
        end
    end

    def create
        @review = Review.new(review_params)
        @review.book_id = @book.id 
        @review.user_id = Current.user.id
        if @review.save
            redirect_to book_path(@book)
        else
            render 'new'
        end
    end

    private

    def review_params
        params.require(:review).permit(:rating, :comment)
    end

    def find_book
        @book = Book.find(params[:book_id])
    end

    def find_review
        @review = Review.find(params[:id])

    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/crew_helper.rb
module CrewHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/reviews/_form.html.erb
<style>
.container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 75vh;
}

form {
  max-width: 500px;
  width: 100%;
}



.form-group {
  margin-bottom: 20px;
}


form input,
textarea,
select {
  width: 100%;
  padding: 10px;
  border: none;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 5px;
  background-color: #fff;
  border: 1px solid #ccc;
}



form select {
  appearance: none;
  -webkit-appearance: none;
  -moz-appearance: none;
  background-image: url('https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-ios7-arrow-down-512.png');
  background-repeat: no-repeat;
  background-position: right 10px center;
  background-size: 12px;
  padding-right: 30px;
}

form input[type="file"] {
  border: none;
  padding: 0;
  margin-top: 5px;
  font-size: 14px;
}



</style>
<div class="container">

<%= simple_form_for([@book, @book.reviews.build]) do |f| %>

      <div class="form-group">
<h1>Add Review </h2>
</div>
      <div class="form-group">

<%= f.input :rating %>
</div>
      <div class="form-group">

<%= f.input :comment %>
</div>

<%= f.button :submit %>

<%end%>
</div>

app/views/reviews/_review.html.erb
<div class="review">
<p class="review-rating"><% review.rating.times do %>
<img src="https://img.freepik.com/premium-vector/yellow-star-icon-vector-illustration_118339-2885.jpg" width="25px" height="25px">
<% end %></p>

<p class="review-comment"><%= review.comment %></p>

      <% if Current.user %>
<% if review.user_id == Current.user.id %>


<div class="links btn-group">

<%= link_to "Edit", edit_book_review_path(review.book, review), class: "btn btn-custom"%>
<%= button_to "Delete", book_review_path(review.book, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom"%>
<%end%>
<%end%>
</div>

app/views/reviews/edit.html.erb
<style>
.container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 75vh;
}

form {
  max-width: 500px;
  width: 100%;
}



.form-group {
  margin-bottom: 20px;
}


form input,
textarea,
select {
  width: 100%;
  padding: 10px;
  border: none;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 5px;
  background-color: #fff;
  border: 1px solid #ccc;
}



form select {
  appearance: none;
  -webkit-appearance: none;
  -moz-appearance: none;
  background-image: url('https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-ios7-arrow-down-512.png');
  background-repeat: no-repeat;
  background-position: right 10px center;
  background-size: 12px;
  padding-right: 30px;
}

form input[type="file"] {
  border: none;
  padding: 0;
  margin-top: 5px;
  font-size: 14px;
}



</style>

<div class="container">



<%= simple_form_for([@book, @review]) do |f| %>
      <div class="form-group">

<h1>Edit Review</h1>
</div>
      <div class="form-group">

<%= f.input :rating %>
</div>
      <div class="form-group">

<%= f.input :comment %>
</div>
<%= f.button :submit %>
<%end%>

app/views/reviews/new.html.erb
<%= render 'form' %>